@startuml timing-pruebas-rendimiento-ibm
!theme bluegray
scale 5 as 150 pixels
title Diagrama de Timing - Pruebas de Rendimiento IBM Cloud Pak\nEscenario: Transferencia Bancaria SWIFT - 5,000 TPS

clock reloj with period 1
binary "Carga Activa" as carga
binary "Base de Datos" as bd
binary "Validación SWIFT" as swift
concise "Tiempo Respuesta" as respuesta
concise "Throughput (TPS)" as tps
concise "CPU %" as cpu
concise "Memoria %" as memoria

@0 as :inicio_warmup
@5 as :inicio_carga_normal
@15 as :pico_carga
@25 as :fin_pico
@35 as :inicio_stress
@45 as :punto_quiebre
@50 as :inicio_recovery
@60 as :fin_prueba

@0
carga is low
bd is low
swift is low
respuesta is "0ms"
tps is "0"
cpu is "20%"
memoria is "30%"

@:inicio_warmup
carga is high
respuesta is "50ms"
tps is "100"

@:inicio_carga_normal-1
bd is high
@:inicio_carga_normal
swift is high
respuesta is "150ms"
tps is "1000"
cpu is "45%"
memoria is "50%"

@10
respuesta is "180ms"
tps is "2500"
cpu is "60%"

@:pico_carga-2
respuesta is "200ms"
tps is "5000"
@:pico_carga
cpu is "70%"
memoria is "75%"

@20
respuesta is "250ms"
tps is "5200"
cpu is "75%"

@:fin_pico
respuesta is "220ms"
tps is "5000"
cpu is "70%"

@30
respuesta is "200ms"
tps is "4800"

@:inicio_stress
respuesta is "400ms"
tps is "7500"
cpu is "85%"
memoria is "85%"

@40
respuesta is "800ms"
tps is "8500"
cpu is "95%"
memoria is "90%"

@:punto_quiebre
carga is low
bd is low
swift is low
respuesta is "ERROR"
tps is "0"
cpu is "98%"
memoria is "95%"

@:inicio_recovery
respuesta is "2000ms"
tps is "500"
cpu is "80%"
memoria is "70%"

@55
respuesta is "300ms"
tps is "2000"
cpu is "50%"

@:fin_prueba
respuesta is "150ms"
tps is "1000"
cpu is "40%"
memoria is "45%"

highlight :inicio_carga_normal to :fin_pico #LightGreen:Carga Normal (SLA Cumplido)
highlight :inicio_stress to :punto_quiebre #Orange:Prueba de Estrés
highlight :punto_quiebre to :inicio_recovery #Red:Punto de Quiebre
highlight :inicio_recovery to :fin_prueba #LightBlue:Recuperación

respuesta@:inicio_carga_normal <-> @:fin_pico : SLA <200ms
tps@:pico_carga -> cpu@:pico_carga : Correlación TPS-CPU
cpu@:punto_quiebre -> memoria@:punto_quiebre : Saturación Recursos

note top of respuesta : Objetivo: <200ms P95
note top of tps : Objetivo: 5,000 TPS sostenido
note top of cpu : Límite: <70% promedio
note bottom of memoria : Límite: <80% heap

@enduml